### ISSUE TITLE
想请教这个库支持人脸去重吗

### ISSUE THREAD

**Issue by Gh0stKnow** [ShiqiYu/libfacedetection#145]

**Comment by nuanxinqing** [comment]
一般人脸去重是基于特征提取的，属于face recognition的范畴。你说的人脸去重是什么？

**Comment by Gh0stKnow** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    应该叫人脸聚合 就是判断为相同的人脸归集到一类 这个属于人脸识别而不是人脸检测的范畴是吗
        
    
        
            
        
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                kidteaing
                            
                    
                        
                            
                                    kidteaing@gmail.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    在2019年4月23日 11:29，Shi Yating<notifications@github.com> 写道： 


一般人脸去重是基于特征提取的，属于face recognition的范畴。你说的人脸去重是什么？



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by nuanxinqing** [comment]
按照你的描述，是属于人脸识别的范畴




------------------ 原始邮件 ------------------
发件人: "Gh0stknow"<notifications@github.com>;
发送时间: 2019年4月23日(星期二) 中午11:31
收件人: "ShiqiYu/libfacedetection"<libfacedetection@noreply.github.com>;
抄送: "婷婷"<824265060@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [ShiqiYu/libfacedetection] 想请教这个库支持人脸去重吗 (#145)



 
 
      
 
 
 
     font{ 
         line-height: 1.6; 
     } 
     ul,ol{ 
         padding-left: 20px; 
         list-style-position: inside; 
     } 
 
 
     
     应该叫人脸聚合 就是判断为相同的人脸归集到一类 这个属于人脸识别而不是人脸检测的范畴是吗
         
     
         
             
         
     
     
      
     
         
                     
             
                 
                     
                             
                                 
                             
                             
                                 kidteaing
                             
                     
                         
                             
                                     kidteaing@gmail.com
                             
                         
                 
             
         
         
     
     
         签名由
         网易邮箱大师
         定制
     
  
 
     在2019年4月23日 11:29，Shi Yating<notifications@github.com> 写道： 
 
 
 一般人脸去重是基于特征提取的，属于face recognition的范畴。你说的人脸去重是什么？
 
 
 
 —You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread. 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by Gh0stKnow** [comment]
已解决 感谢各位
