### ISSUE TITLE
yunet_final.pth模型和转换的YuFaceDetectNet_640.onnx模型在worlds-largest-selfie上检测结果差异大

### ISSUE THREAD

**Issue by Amanda-Barbara** [ShiqiYu/libfacedetection#281]
@ShiqiYu 于老师您好，我使用opencv4.3测试了您发布的dnn模块的人脸检测代码，在阈值设置相同的情况下，发现与原始模型相比，在一同一幅图像上的检测结果差异较大，
![result](https://user-images.githubusercontent.com/38062165/95960017-d08eb100-0e35-11eb-9107-2c88e553fa40.jpg)
![yunetfinalpthresult2](https://user-images.githubusercontent.com/38062165/95960048-d84e5580-0e35-11eb-9e31-06d0156810c7.jpg)

第一幅图是用您写的opencv调用dnn模块代码使用YuFaceDetectNet_640.onnx模型检测的结果，
第二幅图使用您的训练代码中的detect.py代码使用yunet_final.pth模型检测的结果，
请教一下于老师，这个差异是由什么因素导致的？谢谢。

**Comment by fengyuentau** [comment]
@Amanda-Barbara 你好。差异是由于将输入到网络的图片强行resize到640x640造成的。目前opencv的dnn模块只能接受固定输入尺寸的onnx模型，所以我们要固定一个输入的尺寸。而将一张任意比例/大小的图片resize到一个固定的尺寸，比如640x640，会造成人脸变形等，进而影响检测结果。

onnx模型本身是支持任意尺寸输入的。未来opencv的dnn模块更新了对onnx模型的任意尺寸输入的支持，我们也会及时更新代码。

**Comment by Amanda-Barbara** [comment]
@fengyuentau 谢谢您的答疑解惑。

**Comment by Zju-George** [comment]
> @Amanda-Barbara 你好。差异是由于将输入到网络的图片强行resize到640x640造成的。目前opencv的dnn模块只能接受固定输入尺寸的onnx模型，所以我们要固定一个输入的尺寸。而将一张任意比例/大小的图片resize到一个固定的尺寸，比如640x640，会造成人脸变形等，进而影响检测结果。
> 
> onnx模型本身是支持任意尺寸输入的。未来opencv的dnn模块更新了对onnx模型的任意尺寸输入的支持，我们也会及时更新代码。

Is v3 version use fixed size image as input? I found that when use v2 version the result is correct, but the v3 is totally wrong..
Is there any documentation of the difference between the v2 and v3 version?

**Comment by fengyuentau** [comment]
@Amanda-Barbara 现在OpenCV (>=4.5.1) DNN已经支持了ONNX的动态输入，我们的代码已经相应更新了。

**Comment by fengyuentau** [comment]
@Zju-George Previously the OpenCV DNN-based v3 version use fixed-size image as input. However, since OpenCV 4.5.1, it supports dynamic input for ONNX models.

As for your second question, you could open a new issue and offer more details on it. According to our [ChangeLog](https://github.com/ShiqiYu/libfacedetection/blob/master/ChangeLog):
https://github.com/ShiqiYu/libfacedetection/blob/89a88443ff1075de3df06dbffb95d8f2c10c44de/ChangeLog#L1-L10
and also the architecture of [v2](https://netron.app/?url=https://raw.githubusercontent.com/ShiqiYu/libfacedetection/master/models/caffe/yufacedetectnet-open-v2.prototxt) and [v3](https://netron.app/?url=https://raw.githubusercontent.com/ShiqiYu/libfacedetection.train/master/tasks/task1/onnx/YuFaceDetectNet.onnx), there is no difference in terms of network architecture, other than detection heads (v3 has more channels in detection heads for landmarks output).
