### ISSUE TITLE
Face recognition vs. face detection

### ISSUE THREAD

**Issue by josephernest** [ShiqiYu/libfacedetection#282]
Congrats for this nice project @ShiqiYu!
Is it possible to do face recognition with this project? 
i.e. compare if `photo1.jpg` contains the same person as `photo2.jpg`?

(making using of face embedding / encoding and a distance metric?)

Or does it only do face detection?

**Comment by fengyuentau** [comment]
Hi @josephernest . Of course you can try face recognition using the faces detected by this project. However, it is worth noting that face detection is not face recognition, and this project does not perform face recognition. This project is dedicated for face detection, which locates faces on the image, and can be considered as the first step of face recognition, because you need to tell the machine where the face is so as to recognize it.

**Comment by josephernest** [comment]
Thank you for your answer @fengyuentau. So this project is dedicated to locate / detect faces, but *not* dedicated to identify them (e.g. with an 128-dimensional embedding), is that correct?

**Comment by fengyuentau** [comment]
@josephernest Yes, you are right.
